### ISSUE TITLE
Bower install crashes on elastic beanstalk.

### ISSUE THREAD

**Issue by adrianseeley** [froala/wysiwyg-editor-node-sdk#7]
```json
"scripts": {
    "start": "node ./examples/server.js",
    "postinstall": "bower install"
  },
```

Bower install crashes on elastic beanstalk.

**Comment by loicbisiere** [comment]
Same problem on Google Cloud Platform.
Could you please remove the postinstall call and let user execute it manually if needed ?

**Comment by loicbisiere** [comment]
Sorry I saw later that your last commit fixed the problem. To fix temporary the problem (waiting for a new version), you can install the package with this command :  
```npm install --save git+https://github.com/froala/wysiwyg-editor-node-sdk.git#bbd72f5bc6835b365f429fe666dacc7ca426185b```

**Comment by vparpoil** [comment]
@stefanneculai can you publish a new version to npm ? Thanks a lot, it will avoid some future headaches when going to production...
