### ISSUE TITLE
image upload callback get request failed

### ISSUE THREAD

**Issue by theZulqarnain** [froala/wysiwyg-editor-node-sdk#8]
when i'm calling post request `/upload_image` images uploaded in server but it not displaying in editor.
```
router.post('/upload_image', function (req, res) {
    console.log(req.body)
    FroalaEditor.Image.upload(req, '/../public/uploads/', function(err, data) {

        if (err) {
            return res.send(JSON.stringify(err));
        }
        res.send(data);
    });
});
```
**GET /public/uploads/3c1d2db8265758b6954701b3dfb9a8812c4ece3e.png 404 5ms - 2.53kb**

404 error

**Comment by daviddamilola** [comment]
I get the same issue......and when I write a get request for it using regex routes to handle whatever sha1 throws at it....it still says something went wrong try again without logging any errors to the client or server side console!!!

**Comment by sharma-dark-knight** [comment]
@stefanneculai , the path given by user is outside the server.js folder. Upload is successful . But since upload path is outside the server path , it cannot be accessed by server . So user is getting 404 error.If 'public/uploads' is used instead of '../public/uploads/, it will work.
